let db = {
    users: [
        {
            userId: 'asdasgdasyhdaibadhas',
            email: 'user@email.com',
            handle: 'user',
            createdAt: '2011-10-05T14:48:00.000Z',
            imageUrl: 'image/1231415153/asdaadasfaf',
            userLeagues: ['corn liga pro', 'corn liga silver', 'corn liga light'],
            role: 'owner',
            bio: 'this is user bio',
            website: 'http://cornliga.rs',
            location: 'Belgrade, Serbia'
        }
    ],
    leagues: [
        {
            leagueName: 'Corn Liga',
            userHandle: 'filip',
            createdAt: '2011-10-05T14:48:00.000Z',
            website: 'https://cornliga.rs',
            likesCount: '2'
        }
    ],
    teams: [
        {
            leagueId: 'a3g55Fo0ada43',
            teamName: 'Old School',
            teamLogo: 'image/1231415153/asdaadasfaf',
            createdAt: '2011-10-05T14:48:00.000Z',
            //------------------------------------------
            teamAbout: 'Old Skul je amaterska kosarkaska ekipa iz beograda koja okuplja ljude koji vole kosarku, takmicenje i timski duh',
            teamColors: ['crna', 'crvena', 'zuta']
        }
    ],
    players: [
        {
            teamId: 'a3g55Fo0ada43',
            playerName: 'Sava Matkovic',
            playerImage: 'image/1231415153/asdaadasfaf',
            jerseyNumber: '7',
            createdAt: '2011-10-05T14:48:00.000Z',
            //------------------------------------------
            playerPosition: 'sg',
            pleyerHeight: '190',
            seasonsPlayed: ['2019/2020 Old School', '2020/2021 Old School'],
            playerRank: '76',
            freeThrowRank: '16',
            pointsRank: '65',
            threePointRank: '9',
            reboundRank: '131',
            accomplishment: [
                'semi final 2019/2020 Old School',
                'gold medal 2020/2021 Old School'
            ],
            highlights: [{
                gamesPlayed: '13',
                points: '44',
                assists: '16',
                rebounds: '32',
                avergeIndex: '3'
            }]
        }
    ],
    games: [
        {
            leagueId: 'a3g55Fo0ada43',
            gameDateAndTime: '2011-10-05T14:48:00.000Z',
            gameScore: '0-0',
            teams: 'Old School vs Flaming Lions'
        }
    ],
    gameStats: {
        gameId: 'a3g55Fo0ada43',
        teamOneStats: {
            teamName: 'Old School',
            points: '67',
            assists: '7',
            rebounds: '32',
            steals: '5',
            turnovers: '8'
        },
        teamTwoStats: {
            teamName: 'Old School',
            points: '67',
            assists: '7',
            rebounds: '32',
            steals: '5',
            turnovers: '8'
        },
        teamOnePlayerStats: [
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            }
        ],
        teamTwoPlayerStats: [
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            },
            {
                playerName: 'Sava Matkovic',
                points: '16',
                onePointAttempt: '3',
                onePointScore: '3',
                twoPointAttempt: '4',
                twoPointScore: '2',
                threePointAttempt: '6',
                threePointScore: '3',
                fouls: '4',
                foulsDrawn: '2',
                blocks: '0',
                rejected: '1',
                assists: '3',
                steals: '0',
                rebounds: '5',
                offReb: '4',
                defReb: '1',
                turnovers: '2',
                index: '+11',
                scoreOnCourt: '+3'
            }
        ]
    }
};